<a href="https://colab.research.google.com/github/Matheusbcy/-Data-Science-IA-/blob/main/Minera%C3%A7%C3%A3o_de_Dados_do_Linkedin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extração, visualização e análise de dados do Linkedin

## Extração de dados com a API do Linkedin

In [1]:
import string
import random
import requests
import json

## Bases de dados em .csv

In [5]:
import pandas as pd
import plotly.express as px
import numpy as np

In [ ]:
!pip install --upgrade plotly

## Base de dados de conexões

In [ ]:
conexoes = pd.read_csv("/content/Connections.csv")

In [10]:
conexoes.shape

(179, 7)

In [ ]:
conexoes.head(10)

In [12]:
conexoes.drop(labels = ["Email Address"] , axis = 1, inplace = True)

In [ ]:
conexoes

In [ ]:
conexoes.isna().sum()

In [16]:
conexoes.dropna(inplace = True)
conexoes.shape

(150, 6)

In [ ]:
conexoes["Full Name"] = conexoes["First Name"] + " " + conexoes["Last Name"]
conexoes

## Convites

In [20]:
convites = pd.read_csv("/content/Invitations.csv")
convites.columns

Index(['From', 'To', 'Sent At', 'Message', 'Direction', 'inviterProfileUrl',
       'inviteeProfileUrl'],
      dtype='object')

In [21]:
convites.shape

(40, 7)

In [22]:
convites.isna().sum()

From                  0
To                    0
Sent At               0
Message              40
Direction             0
inviterProfileUrl     0
inviteeProfileUrl     0
dtype: int64

In [23]:
convites[convites["Message"].notnull()].head()

Empty DataFrame
Columns: [From, To, Sent At, Message, Direction, inviterProfileUrl, inviteeProfileUrl]
Index: []

In [25]:
convites = convites[convites["Direction"] == "INCOMING"]
convites.shape

(7, 7)

In [26]:
np.unique(convites["Direction"])

array(['INCOMING'], dtype=object)

In [ ]:
convites["Company"] = ""

In [33]:
conexoes[conexoes["Full Name"] == "Matheus Lima"]["Company"].values[0]

'Aprova UFC'

In [38]:
convites = convites.reset_index(drop = True)

In [ ]:
for i in range(0, len(convites)):
  try:
    company = conexoes[conexoes["Full Name"] == convites["From"][i]]["Company"].values[0]
    convites["Company"][i] = company
  except:
    continue

In [54]:
convites.drop(labels = ["From", "To", "Sent At", "Message", "Direction"], axis = 1, inplace = True)

In [56]:
convites.drop(labels = ["inviterProfileUrl", "inviteeProfileUrl"], axis = 1, inplace = True)

In [57]:
convites

                                             Company
0                            Agência Mais Resultados
1                                         Aprova UFC
2  Luminiware: Software e Design para Impulsionar...
3   Gabinete da Vice-Governadoria do Estado do Ceará
4                                            Petlove
5                       Mell Internet - Fibra Óptica
6                                Agrícola Famosa S/A

In [58]:
convites.to_csv("convites.csv")

## Geração de dados fake

In [ ]:
conexoes.drop(labels = ["First Name", "Last Name", "Full Name"], axis = 1, inplace = True)

In [61]:
conexoes.drop(labels = ["URL"], axis = 1, inplace = True)

In [62]:
conexoes

,Company,Position,Connected On
0,Blip,Conversational Strategist Consultant,19 Aug 2025
1,Agência Mais Resultados,Head de Tecnologia,07 Aug 2025
2,Aprova UFC,Desenvolvedor full stack,07 Aug 2025
3,Luminiware: Software e Design para Impulsionar...,Cofundador,06 Aug 2025
4,Gabinete da Vice-Governadoria do Estado do Ceará,Tech Lead,06 Aug 2025
...,...,...,...
174,Clover IT,Cyber Security Analyst,16 Jan 2023
175,Clarke Energia,Analista de Pessoas,04 Jan 2023
176,enjoei,Data Engineer | Engenheira de dados,04 Jan 2023
177,Oficina do Ricardo,Analista de RH,16 Dec 2022
178,ERALDO CONSULTORIA EM DADOS,Estágio em Análise de Dados,31 Jul 2022

In [ ]:
!pip install faker

In [64]:
from faker import Faker

In [66]:
fake = Faker()

In [77]:
fake.name()

'Justin Norris'

In [79]:
conexoes["Full Name"] = ""
conexoes.head()

,Company,Position,Connected On,Full Name
0,Blip,Conversational Strategist Consultant,19 Aug 2025,
1,Agência Mais Resultados,Head de Tecnologia,07 Aug 2025,
2,Aprova UFC,Desenvolvedor full stack,07 Aug 2025,
3,Luminiware: Software e Design para Impulsionar...,Cofundador,06 Aug 2025,
4,Gabinete da Vice-Governadoria do Estado do Ceará,Tech Lead,06 Aug 2025,

In [80]:
conexoes = conexoes.reset_index(drop = True)

In [ ]:
for i in range(0, len(conexoes)):
  conexoes["Full Name"][i] = fake.name()

In [82]:
conexoes

,Company,Position,Connected On,Full Name
0,Blip,Conversational Strategist Consultant,19 Aug 2025,Jared Robinson
1,Agência Mais Resultados,Head de Tecnologia,07 Aug 2025,Joseph Casey
2,Aprova UFC,Desenvolvedor full stack,07 Aug 2025,Anthony Cox
3,Luminiware: Software e Design para Impulsionar...,Cofundador,06 Aug 2025,Dr. Craig Cruz II
4,Gabinete da Vice-Governadoria do Estado do Ceará,Tech Lead,06 Aug 2025,Colton Ross
...,...,...,...,...
145,Clover IT,Cyber Security Analyst,16 Jan 2023,Stacy Alexander
146,Clarke Energia,Analista de Pessoas,04 Jan 2023,Sarah Marquez
147,enjoei,Data Engineer | Engenheira de dados,04 Jan 2023,Jeffrey Hernandez
148,Oficina do Ricardo,Analista de RH,16 Dec 2022,Jessica Reid
149,ERALDO CONSULTORIA EM DADOS,Estágio em Análise de Dados,31 Jul 2022,Nicholas Brown

In [83]:
conexoes.to_csv("conexoes.csv")

# Mensagens

In [84]:
mensagens = pd.read_csv("messages.csv")

In [ ]:
mensagens.columns

In [ ]:
mensagens.shape

## Base de dados de conexões

In [ ]:
mensagens.head(1)

In [ ]:
mensagens = mensagens["CONTENT"]

In [91]:
mensagens.isna().sum()

np.int64(11)

In [92]:
mensagens.dropna(inplace = True)

In [93]:
mensagens.shape

(186,)

# Base de dados de conexões

## Número de conexões por periodo

In [96]:
import datetime
import pandas as pd
import plotly.express as px
import numpy as np

In [ ]:
!pip install --upgrade plotly

In [98]:
conexoes = pd.read_csv("/content/conexoes.csv")
conexoes.drop(labels = ["Unnamed: 0"], axis = 1, inplace = True)

In [99]:
conexoes.head()

,Company,Position,Connected On,Full Name
0,Blip,Conversational Strategist Consultant,19 Aug 2025,Jared Robinson
1,Agência Mais Resultados,Head de Tecnologia,07 Aug 2025,Joseph Casey
2,Aprova UFC,Desenvolvedor full stack,07 Aug 2025,Anthony Cox
3,Luminiware: Software e Design para Impulsionar...,Cofundador,06 Aug 2025,Dr. Craig Cruz II
4,Gabinete da Vice-Governadoria do Estado do Ceará,Tech Lead,06 Aug 2025,Colton Ross

In [101]:
def converter_data(data):
  return datetime.datetime.strptime(data, "%d %b %Y").strftime("%Y-%m-%d")

In [102]:
 conexos["Connected On"] = conexoes["Connected On"].apply(converter_data)

In [103]:
conexoes

,Company,Position,Connected On,Full Name
0,Blip,Conversational Strategist Consultant,2025-08-19,Jared Robinson
1,Agência Mais Resultados,Head de Tecnologia,2025-08-07,Joseph Casey
2,Aprova UFC,Desenvolvedor full stack,2025-08-07,Anthony Cox
3,Luminiware: Software e Design para Impulsionar...,Cofundador,2025-08-06,Dr. Craig Cruz II
4,Gabinete da Vice-Governadoria do Estado do Ceará,Tech Lead,2025-08-06,Colton Ross
...,...,...,...,...
145,Clover IT,Cyber Security Analyst,2023-01-16,Stacy Alexander
146,Clarke Energia,Analista de Pessoas,2023-01-04,Sarah Marquez
147,enjoei,Data Engineer | Engenheira de dados,2023-01-04,Jeffrey Hernandez
148,Oficina do Ricardo,Analista de RH,2022-12-16,Jessica Reid
149,ERALDO CONSULTORIA EM DADOS,Estágio em Análise de Dados,2022-07-31,Nicholas Brown

In [104]:
grafico = px.scatter(conexoes, x = "Full Name", y = "Connected On")
grafico.show()

In [ ]:
conexoes.groupby(by = "Connected On").count()

In [106]:
grafico = px.line(conexoes.groupby(by = "Connected On").count(), title = "Novas conexões por data")
grafico.show()

In [107]:
conexoes

,Company,Position,Connected On,Full Name
0,Blip,Conversational Strategist Consultant,2025-08-19,Jared Robinson
1,Agência Mais Resultados,Head de Tecnologia,2025-08-07,Joseph Casey
2,Aprova UFC,Desenvolvedor full stack,2025-08-07,Anthony Cox
3,Luminiware: Software e Design para Impulsionar...,Cofundador,2025-08-06,Dr. Craig Cruz II
4,Gabinete da Vice-Governadoria do Estado do Ceará,Tech Lead,2025-08-06,Colton Ross
...,...,...,...,...
145,Clover IT,Cyber Security Analyst,2023-01-16,Stacy Alexander
146,Clarke Energia,Analista de Pessoas,2023-01-04,Sarah Marquez
147,enjoei,Data Engineer | Engenheira de dados,2023-01-04,Jeffrey Hernandez
148,Oficina do Ricardo,Analista de RH,2022-12-16,Jessica Reid
149,ERALDO CONSULTORIA EM DADOS,Estágio em Análise de Dados,2022-07-31,Nicholas Brown

In [109]:
conexoes["Connected On"] = pd.to_datetime(conexoes["Connected On"])

In [110]:
conexoes["ano"] = conexoes["Connected On"].dt.year
conexoes["mes"] = conexoes["Connected On"].dt.month

In [115]:
grafico = px.line(conexoes.groupby(by = "ano").count(), title = "Novas conexões por ano")
grafico.show()

In [114]:
grafico = px.line(conexoes.groupby(by = "mes").count(), title = "Novas conexões por mes")
grafico.show()

### Empresas

In [116]:
np.unique(conexoes["Company"], return_counts = True)

(array(['6XPHERE World Business', '9TALK Agency', '@pec', 'A.R.Phoenix',
        'ATI - Agência Estadual de Tecnologia da Informação / PE',
        'Accenture Brasil', 'Acid Labs', 'AgroThathi',
        'Agrícola Famosa S/A', 'Agência Mais Resultados',
        'Akamai Technologies', 'Aprova UFC', 'Arcos Dorados', 'Atos',
        'Autônomo', 'Autônomo desenvolverdor front-end', 'Avenida', 'BG10',
        'Before', 'Blip', 'Brisanet Telecomunicações', 'CI&T',
        'CRVA Zona Sul', 'CWI Software', 'Central dos Benefícios',
        'Clarke Energia', 'Clover IT', 'Comercio Varejista MG',
        'Contabilidade Jose Santos', 'Correia & Assossiados Contadores',
        'Correio Braziliense', 'DBSoft Informática - Automação Comercial',
        'DIO', 'Decola Juninho', 'Devzapp⚡', 'ERALDO CONSULTORIA EM DADOS',
        'Escola Estatual Coronel Ernesto Schmiddt', 'Estúdio PUYA!',
        'ExitLag', 'FTD Educação', 'FitBank', 'Fox English Brazil',
        'Freelance', 'Frutop',
        'Gabinete da Vice-Governadoria do Estado do Ceará',
        'Gaigher & Cia Psicanálise Clinica', 'Grupo Actcon',
        'Grupo Equatorial', 'Grupo Primavia', 'Grupo Vamos',
        'Grupo Voetur', 'Hapvida NotreDame Intermédica',
        'Hospital Mestre Vitalino',
        'Hospital Veterinário São Francisco de Assis',
        'I-Vtec Solucao Em Informatica Ltda - Me',
        'I.V.Tecnologias Web Ltda', 'IAuto Brasil', 'IBM',
        'IMP Soluções Digitais', 'Infarma Sistemas',
        'Info Service Desk LTDA', 'Innovation Brindes',
        'Instituto Esporte & Educação', 'Intelecta Games', 'Intermarine',
        'Interseg', 'Invillia', 'Invision Geofísica',
        'Isapa Importadora e Distribuidora de Autopeças',
        'Itia - Instituto de Tecnologia e Inteligência Artificial',
        'Ius | Tecnologia que Simplifica a Gestão de Requisitos Legais e ESG',
        'JW Coworking', 'Jones Software', 'Jusbrasil',
        'Kairós Fardamentos', 'Kalitech Powertrain Calibration', 'Kunumi',
        'LHC Assessoria Empresarial', 'Laboratório Sobral', 'Linx',
        'Louzada Tech',
        'Luminiware: Software e Design para Impulsionar Negócios',
        'M. Dias Branco', 'MSB Tecnologia',
        'Marluvas Equipamentos Profissionais',
        'Mell Internet - Fibra Óptica', 'Mentoria em desenvolvimento web.',
        'Mercado Livre', 'Muralha Digital Sentry', 'Nerds UFC',
        'Oficina do Ricardo', 'Okai Compliance', 'PONTTONLINE',
        'PREFEITURA MUNICIPAL DE SANTA ISABEL', 'Petlove', 'Porto',
        'Prefeitura Municipal de Franca', 'Primeira Mão by Saga',
        'Prolog Informatica', 'RCX Tecnologia de Negócios',
        'Reserve Systems', 'Rodoagro', 'Routinely',
        'Sacre Investimentos - AI do BTG Pactual', 'Sagez IT Solutions',
        'Schalter Tecnologia', 'Se-Connect - Capivari de Baixo',
        'Select Soluções', 'Sensual moda íntima',
        'Seuma Secretaria Municipal de Urbanismo e Meio Ambiente',
        'Seven Educação', 'Shopper.com.br', 'SiDi', 'SigSaúde/SESAP',
        'Sistema FIEC', 'Sistema SIVI', 'Sister ', 'Solar Coca-Cola',
        'Supermercado Mais Você', 'SysMap Solutions', 'TIM Brasil',
        'Tem Vaga Mestre?', 'Thoughtworks', 'Transoares', 'Tua Agenda',
        'Unimed Fortaleza', 'Universidade Federal do Ceará',
        'Universidade Federal do Ceará (UFC)', 'Universidade Paulista',
        'Universidade do Trabalho Digital', 'Vindicce', 'Viveo', 'Voltz',
        'Youx Group', 'ZENVIA', 'dsm-firmenich', 'enjoei', 'freelance',
        'gente seguradora', 'gsurf', 'iFood',
        'ibyte. Mais que tecnologia.', 'lignet'], dtype=object),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [117]:
conexoes.shape

(150, 6)

In [118]:
len(np.unique(conexoes["Company"]))

143

In [119]:
grafico = px.histogram(conexoes["Company"])
grafico.show()

In [122]:
grafico = px.treemap(conexoes, path = ["Company", "Position", "Full Name"])
grafico.show()

### Cargos

In [123]:
np.unique(conexoes["Position"], return_counts = True)

(array([' Data Engineer | Engenheira de dados',
        ' Talent Acquisition Manager', 'Administrador', 'Advogado',
        'Agente de Administração Pública', 'Aluno', 'Analista Suporte N.2',
        'Analista TI JR I', 'Analista de BI - Planejamento e Growth',
        'Analista de Dados Pleno / Business Inteligence',
        'Analista de Faturamento', 'Analista de Pessoas', 'Analista de RH',
        'Analista de TI', 'Analista de desenvolvimento Pleno',
        'Analista de infraestrutura de TI', 'Analista de sistema',
        'Analista de suporte a computadores',
        'Analista de suporte computacional', 'Analista de suporte júnior',
        'Analista de tecnologia da informação - Front-End',
        'Analista financeiro', 'Analyst - Network Protection Assurance',
        'Application Developer', 'Arquiteto de Soluções DevOps AWS',
        'Assistente Administrativo', 'Assistente administrativo',
        'Auditor internacional', 'Auxiliar administrativo logístico ',
        'Auxiliar de atendimento ao cliente', 'Auxiliar de escritório',
        'Auxiliar de produção', 'Back End Developer', 'Back-end Developer',
        'CEO', 'Chefe de TI', 'Cloud Support Engineer', 'Cofundador',
        'Cofundadora', 'Commercial Manager', 'Comprador',
        'Consultor SAP Basis Security Pleno',
        'Consultora de desenvolvimento',
        'Conversational Strategist Consultant', 'Coordenador financeiro',
        'Cyber Security Analyst', 'Data Scientist - Analyst',
        'Desenvolvedor  Back-end', 'Desenvolvedor .NET',
        'Desenvolvedor Front-end', 'Desenvolvedor Front-end Pleno',
        'Desenvolvedor Full Stack Júnior', 'Desenvolvedor Full-stack',
        'Desenvolvedor da web', 'Desenvolvedor de front-end',
        'Desenvolvedor de software',
        'Desenvolvedor front-end - Voluntário',
        'Desenvolvedor front-end pleno', 'Desenvolvedor full stack',
        'Desenvolvedor full stack pleno', 'Desenvolvedor júnior',
        'Desenvolvedor trainee', 'Desenvolvedora Junior',
        'Desenvolvedora de back end', 'Desenvolvedora full stack',
        'Desenvolvendora Front End ', 'Designer gráfico', 'Developer',
        'Dio Campus Expert ', 'Diretor de Automação',
        'Diretor de tecnologia', 'Docente universitário', 'Eletricista',
        'Eletricista de embarcações', 'Engenheira de Software Jr',
        'Engenheiro de dados', 'Especialista de Dados RPA e IA',
        'Estagiário', 'Estagiário (Atuando como analista de Suporte)',
        'Estagiário de desenvolvimento', 'Estágio em Análise de Dados',
        'Estágio em Ciências Contábeis', 'Executivo de vendas',
        'Financial Support Analyst',
        'Frontend Software Engineer | Next.js | React.js | Typescript',
        'Full Account Executive', 'Full Stack Developer',
        'Full Stack Engineer', 'Gerente comercial', 'Gerente de TI',
        'Gerente de criação', 'Gerente de processos', 'Gerente geral',
        'Gestor financeiro', 'HR Business Partner', 'Head de Tecnologia',
        'Inspetora de alunos', 'Instrutora', 'Java Back-end Developer',
        'Junior Data Engineer ', 'Junior Software Developer',
        'Líder de engenharia', 'Líder de implementação',
        'Mentoria em Desenvolvimento Web', 'Microempreendedor',
        'Mid-Level Data Engineer',
        'Mid-Level Software Engineering Analyst', 'Monitor arqueólogico',
        'Orientadora Esportiva', 'Prestador de serviços',
        'Principal Data Scientist', 'Product Designer',
        'Produtora de conteúdo', 'Professor de Informática e Programação',
        'Programador', 'Programador de software', 'Psicanalista',
        'Repositor', 'Researcher', 'SDR', 'Software Developer',
        'Software Engineer', 'Software Engineer Frontend',
        'Strategic Planning Coordinator', 'Sucesso do cliente',
        'Suporte Técnico N1 (Noc)', 'Suporte de internet',
        'Suporte técnico', 'Tech Lead',
        'Tech Recruiter - Assistente de RH', 'Tech Recruiter Sênior',
        'Técnico de computador', 'Técnico de hardware ', 'Veterinário',
        'Vistoriador', '💻 Suporte Técnico em TI | MSB Tecnologia'],
       dtype=object),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 4, 2, 1, 1, 1, 1, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1]))

In [124]:
conexoes.shape

(150, 6)

In [125]:
len(np.unique(conexoes["Position"]))

136

In [130]:
def altera_cargo(cargo):
  novo_cargo = cargo
  if cargo == "Desenvolvedora full stack":
    novo_cargo = "Desenvolvedor full stack"
  return novo_cargo

In [132]:
conexoes["Position"] = conexoes["Position"].apply(altera_cargo)

In [133]:
grafico = px.histogram(conexoes["Position"])
grafico.show()

In [134]:
grafico = px.treemap(conexoes, path = ["Position", "Company", "Full Name"])
grafico.show()